# Generated by Django 3.1.7 on 2021-12-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_homes', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Other_r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_rs', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.PositiveSmallIntegerField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='main.product')),
            ],
        ),
    ]
