# Generated by Django 3.1.7 on 2021-12-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_favourite'),
        ('real_estate', '0003_auto_20211130_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_r',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_rs', to='main.product'),
        ),
    ]
