# Generated by Django 3.1.7 on 2021-12-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('benzin', 'benzin'), ('elektr', 'elektr'), ('dizel', 'dizel')], max_length=6)),
                ('year_issue', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('mexanika', 'mexanika'), ('avtomat', 'avtomat')], max_length=8)),
                ('air_condition', models.BooleanField()),
                ('position', models.CharField(max_length=1)),
                ('mileage', models.IntegerField()),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.bodytype')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.color')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.model')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('benzin', 'benzin'), ('elektr', 'elektr'), ('dizel', 'dizel')], max_length=6)),
                ('year_issue', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('mexanika', 'mexanika'), ('avtomat', 'avtomat')], max_length=8)),
                ('air_condition', models.BooleanField()),
                ('position', models.CharField(max_length=1)),
                ('mileage', models.IntegerField()),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.bodytype')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.color')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.model')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specials', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Other_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('benzin', 'benzin'), ('elektr', 'elektr'), ('dizel', 'dizel')], max_length=6)),
                ('year_issue', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('mexanika', 'mexanika'), ('avtomat', 'avtomat')], max_length=8)),
                ('air_condition', models.BooleanField()),
                ('position', models.CharField(max_length=1)),
                ('mileage', models.IntegerField()),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.bodytype')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.color')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.model')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_ts', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('benzin', 'benzin'), ('elektr', 'elektr'), ('dizel', 'dizel')], max_length=6)),
                ('year_issue', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('mexanika', 'mexanika'), ('avtomat', 'avtomat')], max_length=8)),
                ('air_condition', models.BooleanField()),
                ('position', models.CharField(max_length=1)),
                ('mileage', models.IntegerField()),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.bodytype')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.color')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.model')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Agricultural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('benzin', 'benzin'), ('elektr', 'elektr'), ('dizel', 'dizel')], max_length=6)),
                ('year_issue', models.PositiveSmallIntegerField()),
                ('transmission', models.CharField(choices=[('mexanika', 'mexanika'), ('avtomat', 'avtomat')], max_length=8)),
                ('air_condition', models.BooleanField()),
                ('position', models.CharField(max_length=1)),
                ('mileage', models.IntegerField()),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.bodytype')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.color')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.model')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agriculturals', to='main.product')),
            ],
        ),
    ]
