# Generated by Django 3.1.7 on 2021-12-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_model_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytype',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/'),
        ),
    ]
