# Generated by Django 3.1.7 on 2021-11-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_location'),
        ('transport', '0002_auto_20211130_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other',
            new_name='Other_t',
        ),
    ]
